server:
  port: 8761

spring:
  application:
    name: discovery

  threads:
    virtual:
      enabled: true
#  config:
#    import: optional:configserver:http://configUser:configPass@localhost:8882
#    fail-fast: true

eureka:
  server:
    peer-node-read-timeout-ms: 10000
    peer-node-connect-timeout-ms: 5000
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://${eureka.security.username}:${eureka.security.password}@localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 45
    hostname: localhost
    prefer-ip-address: false
  security:
    username: switchUser
    password: password123

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always